steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/github.com/jon890/piu-db:${COMMIT_SHA}",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/github.com/jon890/piu-db:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
