steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/piudb-web:$COMMIT_SHA .
    automapSubstitutions: true
images:
  - "asia-northeast3-docker.pkg.dev/$PROJECT_ID/piudb-web:$COMMIT_SHA/$PROJECT_ID/piudb-web:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
