steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/piudb-web:${COMMIT_SHA}",
        ".",
      ]
images:
  - "asia-northeast3-docker.pkg.dev/$PROJECT_ID/piudb-web:$COMMIT_SHA/$PROJECT_ID/piudb-web:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
