import { SongData } from "./song-type";

export const PHOENIX_SONGS: SongData[] = [
  {
    name: "보카",
    artist: "드림캐쳐",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
  },

  {
    name: "누드",
    artist: "(여자)아이들",
    bpm: "136",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "테디베어",
    artist: "스테이씨",
    bpm: "119",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "얼론",
    artist: "하이라이트",
    bpm: "115",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
  },

  {
    name: "아모르 파티",
    artist: "김연자",
    bpm: "135",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
  },

  {
    name: "애프터 라이크",
    artist: "아이브",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 7, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "일레븐",
    artist: "아이브",
    bpm: "120",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "파이렛",
    artist: "에버글로우",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
  },

  {
    name: "톰보이",
    artist: "(여자)아이들",
    bpm: "124",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "위스퍼",
    artist: "더보이즈",
    bpm: "96",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
  },

  {
    name: "스프레이",
    artist: "위아이",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
    ],
  },

  {
    // TODO 7
    name: "뷰티풀라이어",
    artist: "아이브",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 7, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    // TODO 7
    name: "판도라",
    artist: "메이브",
    bpm: "75",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
  },

  {
    // TODO 7
    name: "스톰",
    artist: "아이브",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 7, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "비행기",
    artist: "타이푼",
    bpm: "120",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 3, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
  },

  {
    name: "스톰",
    artist: "코요태",
    bpm: "139",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
    ],
  },

  {
    name: "뷰티풀라이어",
    artist: "몬스타엑스",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 9, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
  },

  {
    name: "벡터",
    artist: "Zekk",
    bpm: "174",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "베르사이유",
    artist: "HyuN & MIIM",
    bpm: "160-175",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
  },

  {
    name: "쇼다운",
    artist: "litmus*",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 6, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "붐!!",
    artist: "RiraN",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    // 10
    name: "유포리아닉",
    artist: "SHK",
    bpm: "140",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 10, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
  },

  {
    name: "할로윈 파티 ~Multiverse~",
    artist: "SHK",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    // 11
    name: "쥬핀",
    artist: "Sobrem",
    bpm: "173",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
  },

  {
    name: "그로스",
    artist: "nato",
    bpm: "212",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
  },

  {
    name: "꼭두각시",
    artist: "onoken",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 25, chartType: "SINGLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
      { level: 27, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "플레이버 스텝!",
    artist: "EmoCosine",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "추격",
    artist: "MAX",
    bpm: "176",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "라크리모사",
    artist: "Fiverwater",
    bpm: "210",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 9, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 222, chartType: "DOUBLE" },
    ],
  },

  {
    name: "머독",
    artist: "WONDERTRAVELER Project",
    bpm: "179",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "바버스 매드니스",
    artist: "Klass E",
    bpm: "195",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "요! 세이!! 페어리!!!",
    artist: "MYUKKE.",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "블루이쉬 로즈",
    artist: "WyvernP",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
  },

  {
    name: "록시아",
    artist: "The Musical Ghost",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "네오 카타르시스",
    artist: "TAG underground overlay",
    bpm: "120-300",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 13, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 25, chartType: "SINGLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 27, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "큐리아서티 오버드라이브",
    artist: "t+pazolite",
    bpm: "192",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "카오스 어게인",
    artist: "NAOKI underground -Ω-",
    bpm: "150-260",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "갤럭시 컬랩스",
    artist: "Kurokotei",
    bpm: "150-320",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "굿텍",
    artist: "EBIMAYO",
    bpm: "190",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "코스믹 레일로드",
    artist: "kanone",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "에너지 시너지 매트릭스",
    artist: "Tanchiky",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "밀크",
    artist: "MoriMori Atsushi",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "어콰이어",
    artist: "ryhki",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "진폐증 ft. Kagamine Len/GUMI",
    artist: "DASU",
    bpm: "156",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
  },

  {
    name: "알테일",
    artist: "sakuzyo",
    bpm: "90",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "이렐리아",
    artist: "HyuN",
    bpm: "204",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
  },

  {
    name: "굿바운스",
    artist: "EBIMAYO",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },

  {
    name: "R.I.P",
    artist: "eicateve",
    bpm: "192",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "푸파",
    artist: "Morimori Atsushi",
    bpm: "202",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "아라가미",
    artist: "xi",
    bpm: "48-196",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
  },

  {
    name: "할시온",
    artist: "xi",
    bpm: "40-191",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "비옐라의 악몽",
    artist: "Laur",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
  },

  {
    name: "트릭크래쉬 220",
    artist: "Lite Show Magic",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
  },

  {
    name: "배틀 넘버원",
    artist: "TANO*C Sound Team",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
  },

  {
    name: "유포리아닉 - SHORT CUT",
    artist: "SHK",
    bpm: "140",
    version: "PHOENIX",
    songType: "SHORT_CUT",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
    ],
  },

  // 1.07
  {
    name: "서든 어페어런스 이미지",
    artist: "Blacklolita",
    bpm: "170",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
  },

  {
    name: "시",
    artist: "Doin",
    bpm: "293",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 2, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
  },

  {
    name: "사이먼 세이즈, 유로댄스!! (feat. Sara☆M)",
    artist: "Jehezukiel☆KAZEMURA☆Hideky",
    bpm: "157",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
  },

  {
    name: "리틀 먼치킨",
    artist: "Castellia",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.07",
  },

  {
    name: "스테이저",
    artist: "Ras",
    bpm: "146",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
  },
];
