import { SongData } from "./song-type";

export const PHOENIX_SONGS: SongData[] = [
  {
    name: "보카",
    artist: "드림캐쳐",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/eb5af940defb17449259e75e16926870.png",
  },

  {
    name: "누드",
    artist: "(여자)아이들",
    bpm: "136",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/7b6237f4583cab1dd1a1b1f85264eaa5.png",
  },

  {
    name: "테디베어",
    artist: "스테이씨",
    bpm: "119",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/5c0a9e5e699863547ef7fa8d6485fc4a.png",
  },

  {
    name: "얼론",
    artist: "하이라이트",
    bpm: "115",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/f1bc02103c6dc2b47d08cef830176035.png",
  },

  {
    name: "아모르 파티",
    artist: "김연자",
    bpm: "135",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/46f545d32d421f3b6d7bd7d67531173e.png",
  },

  {
    name: "애프터 라이크",
    artist: "아이브",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 7, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/ed7e43efd28eba896f90b94ff1ebc06f.png",
  },

  {
    name: "일레븐",
    artist: "아이브",
    bpm: "120",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.04",
    imageUrl:
      "https://www.piugame.com/data/song_img/e0cf19dbb807e5d3f2efa3db5ca163a0.png",
  },

  {
    name: "파이렛",
    artist: "에버글로우",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/a349e92cde3a219d72d082c9ed7deade.png",
  },

  {
    name: "톰보이",
    artist: "(여자)아이들",
    bpm: "124",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.06",
    imageUrl:
      "https://www.piugame.com/data/song_img/ec342950e66150e76a00b09492dfda3c.png",
  },

  {
    name: "위스퍼",
    artist: "더보이즈",
    bpm: "96",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
    patchVersion: "1.03",
    imageUrl:
      "https://www.piugame.com/data/song_img/821e012731725917d2365e1352ad028f.png",
  },

  {
    name: "스프레이",
    artist: "위아이",
    bpm: "125",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
    ],
    patchVersion: "1.05",
    imageUrl:
      "https://www.piugame.com/data/song_img/d89b413ad14fae24007dfdd77a387d6c.png",
  },

  {
    name: "판도라",
    artist: "메이브",
    bpm: "75",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
    ],
    patchVersion: "1.06",
    imageUrl:
      "https://www.piugame.com/data/song_img/45a186e942deff08bc88bf9141e2d1dd.png",
  },

  {
    name: "비행기",
    artist: "타이푼",
    bpm: "120",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 1, chartType: "SINGLE" },
      { level: 3, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/f47eb7519299f8c8e848d95c6cc74967.png",
  },

  {
    name: "스톰",
    artist: "코요태",
    bpm: "139",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/50c49e67d330d6bd6d84b04da8afaa2a.png",
  },

  {
    name: "뷰티플라이어",
    artist: "몬스타엑스",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 9, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
    ],
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/fdcba58abc4ae2ed3ab20da10aec0fd0.png",
  },

  {
    name: "벡터",
    artist: "Zekk",
    bpm: "174",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/ab914c8ca7030b776ec3cd3ad7dad3e9.png",
  },

  {
    name: "베르사이유",
    artist: "HyuN & MIIM",
    bpm: "160-175",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/305329152cdd89f6229dec2a3074c18b.png",
  },

  {
    name: "쇼다운",
    artist: "litmus*",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 6, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/7387703a9867124dd6159fd3ee0b8094.png",
  },

  {
    name: "붐!!",
    artist: "RiraN",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/9caa31f81ba859eb53adc2b47b6d93bc.png",
  },

  {
    name: "유포리아닉",
    artist: "SHK",
    bpm: "140",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 10, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/7e1af52be6d8b4e147d2a0ebbf54ef98.png",
  },

  {
    name: "할로윈 파티 ~Multiverse~",
    artist: "SHK",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.03",
    imageUrl:
      "https://www.piugame.com/data/song_img/6175376a00ff0d561bab24934e04b782.png",
  },

  {
    name: "쥬핀",
    artist: "Sobrem",
    bpm: "173",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/9f561790e1f3df1f1174b87f0d78b9d6.png",
  },

  {
    name: "그로스",
    artist: "nato",
    bpm: "212",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/711e60a1b06997e72dde2024731aebdf.png",
  },

  {
    name: "꼭두각시",
    artist: "onoken",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 25, chartType: "SINGLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
      { level: 27, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/6b61fae3e35139975deb1199f1ad550a.png",
  },

  {
    name: "플레이버 스텝!",
    artist: "EmoCosine",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.06",
    imageUrl:
      "https://www.piugame.com/data/song_img/2eecbab75fb2d9f0f95971ff487fc934.png",
  },

  {
    name: "추격",
    artist: "MAX",
    bpm: "176",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/584749a3cecd3f4b5714df28cd502d14.png",
  },

  {
    name: "라크리모사",
    artist: "Fiverwater",
    bpm: "210",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 9, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.03",
    imageUrl:
      "https://www.piugame.com/data/song_img/56fbd3887c1f170ff0bab5fd5bac7320.png",
  },

  {
    name: "머독",
    artist: "WONDERTRAVELER Project",
    bpm: "179",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/8eb8a3021756670ce067a3ef7cfb9f2a.png",
  },

  {
    name: "바버스 매드니스",
    artist: "Klass E",
    bpm: "195",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.04",
    imageUrl:
      "https://www.piugame.com/data/song_img/d24baf611d258d15c997afc26b6380fe.png",
  },

  {
    name: "요! 세이!! 페어리!!!",
    artist: "MYUKKE.",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.05",
    imageUrl:
      "https://www.piugame.com/data/song_img/1afce79a91b11aacedfadb6f8f0c360c.png",
  },

  {
    name: "블루이쉬 로즈",
    artist: "WyvernP",
    bpm: "130",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 5, chartType: "SINGLE" },
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
    patchVersion: "1.06",
    imageUrl:
      "https://www.piugame.com/data/song_img/03b6b88c054909e454b57dd7b7dfb831.png",
  },

  {
    name: "록시아",
    artist: "The Musical Ghost",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/280eaf79c3414fcc25d52691f550a624.png",
  },

  {
    name: "네오 카타르시스",
    artist: "TAG underground overlay",
    bpm: "120-300",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 13, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 25, chartType: "SINGLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 27, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.04",
    imageUrl:
      "https://www.piugame.com/data/song_img/14cd5d7a3df1f12b82bccec2faea2705.png",
  },

  {
    name: "큐리아서티 오버드라이브",
    artist: "t+pazolite",
    bpm: "192",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.05",
    imageUrl:
      "https://www.piugame.com/data/song_img/2cf6b048170d3446cbb27e722a1d805f.png",
  },

  {
    name: "카오스 어게인",
    artist: "NAOKI underground -Ω-",
    bpm: "150-260",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/df2bb22858f58b4cf088ce1866854f2d.png",
  },

  {
    name: "갤럭시 컬랩스",
    artist: "Kurokotei",
    bpm: "150-320",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.03",
    imageUrl:
      "https://www.piugame.com/data/song_img/f89ff0cf996937d690d7ebb7502e6c1e.png",
  },

  {
    name: "굿텍",
    artist: "EBIMAYO",
    bpm: "190",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/08a55debe196a4c44b2041868a5c2070.png",
  },

  {
    name: "코스믹 레일로드",
    artist: "kanone",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 10, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/cb4ad7cf62655b7d2907ade4d781873f.png",
  },

  {
    name: "에너지 시너지 매트릭스",
    artist: "Tanchiky",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/9a9a1a662444b7305346e031dad8be2e.png",
  },

  {
    name: "밀크",
    artist: "MoriMori Atsushi",
    bpm: "150",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/4f6cd22fb830dcc99d53fcd91066e255.png",
  },

  {
    name: "어콰이어",
    artist: "ryhki",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/b41eaa298c4c19f0dedc11e75271e353.png",
  },

  {
    name: "진폐증 ft. Kagamine Len/GUMI",
    artist: "DASU",
    bpm: "156",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/3f60d49fc1d14e5cfa51e8c90eec847b.png",
  },

  {
    name: "알테일",
    artist: "sakuzyo",
    bpm: "90",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 6, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/3aed0157e26dfa040bf84ae1167a22d5.png",
  },

  {
    name: "이렐리아",
    artist: "HyuN",
    bpm: "204",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    patchVersion: "1.05",
    imageUrl:
      "https://www.piugame.com/data/song_img/282c1e3e7427966fe98c2fb2accfa9d6.png",
  },

  {
    name: "굿바운스",
    artist: "EBIMAYO",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/fb318d836ec65eca2c99728fee9f3dc9.png",
  },

  {
    name: "R.I.P",
    artist: "eicateve",
    bpm: "192",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/1fdba3fa2fd7fc9c3fef0593fb67897d.png",
  },

  {
    name: "푸파",
    artist: "Morimori Atsushi",
    bpm: "202",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.05",
    imageUrl:
      "https://www.piugame.com/data/song_img/adf1054211294efcbfb92ac97a37ec75.png",
  },

  {
    name: "아라가미",
    artist: "xi",
    bpm: "48-196",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    patchVersion: "1.04",
    imageUrl:
      "https://www.piugame.com/data/song_img/268d0e5526dc475ccf8ca90a60fcae68.png",
  },

  {
    name: "할시온",
    artist: "xi",
    bpm: "40-191",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.00",
    imageUrl:
      "https://www.piugame.com/data/song_img/51fcd45896e9b9925e3e1f0a77556e24.png",
  },

  {
    name: "비옐라의 악몽",
    artist: "Laur",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "1.04",
    imageUrl:
      "https://www.piugame.com/data/song_img/dde154d8a721c5d510b71c788d0b8673.png",
  },

  {
    name: "트릭크래쉬 220",
    artist: "Lite Show Magic",
    bpm: "220",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    isPremium: true,
    patchVersion: "1.06",
    imageUrl:
      "https://www.piugame.com/data/song_img/81c807da9ac1fd29e74ab8a510976789.png",
  },

  {
    name: "배틀 넘버원",
    artist: "TANO*C Sound Team",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.02",
    imageUrl:
      "https://www.piugame.com/data/song_img/12452411f0fddba3caf2382c9bf033f4.png",
  },

  {
    name: "유포리아닉 - SHORT CUT -",
    artist: "SHK",
    bpm: "140",
    version: "PHOENIX",
    songType: "SHORT_CUT",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 10, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
    ],
    patchVersion: "1.03",
    imageUrl:
      "https://www.piugame.com/data/song_img/a69635c7e3a9ddd1e9a2e3a05ac07d48.png",
  },

  {
    name: "서든 어페어런스 이미지",
    artist: "Blacklolita",
    bpm: "170",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
    imageUrl:
      "https://www.piugame.com/data/song_img/b2bd709009f25a9ac3618390c7b9917e.png",
  },

  {
    name: "시",
    artist: "Doin",
    bpm: "293",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 2, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
    imageUrl:
      "https://www.piugame.com/data/song_img/2e0daf0c0eb3b5a188a20eb0a7dd1581.png",
  },

  {
    name: "사이먼 세이즈, 유로댄스!! (feat. Sara☆M)",
    artist: "Jehezukiel☆KAZEMURA☆Hideky",
    bpm: "157",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.07",
    imageUrl:
      "https://www.piugame.com/data/song_img/ecc05e7a2615a2a2770e4a8c5487eb4c.png",
  },

  {
    name: "리틀 먼치킨",
    artist: "Castellia",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.07",
    imageUrl:
      "https://www.piugame.com/data/song_img/d59295bf426a99e64848df63ced40717.png",
  },

  {
    name: "스테이저",
    artist: "Ras",
    bpm: "146",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 12, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 50, chartType: "CO_OP" },
    ],
    patchVersion: "1.07",
    imageUrl:
      "https://www.piugame.com/data/song_img/07e7d5fd7daa31f830fea74250cc2186.png",
  },

  // 1.08
  {
    name: "솔페지에토",
    artist: "Fiverwater",
    bpm: "157",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 9, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "1.08",
    imageUrl:
      "https://www.piugame.com/data/song_img/89ad08817eede5a099583987e96d64b3.png",
  },

  {
    name: "루시드 드림",
    artist: "Cosmograph",
    bpm: "173",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 8, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "1.08",
    imageUrl:
      "https://www.piugame.com/data/song_img/bd82e2ff6db9c6e4ba585760cb5a94f7.png",
  },

  {
    name: "디스트로0ㅣ어",
    artist: "sakuzyo",
    bpm: "90",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 7, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "1.08",
    imageUrl:
      "https://www.piugame.com/data/song_img/1cdf3c4a70abd903f51f0f9e969830ee.png",
  },

  {
    name: "피가로의 결혼 ~Celebrazione Remix~",
    artist: "Sr. Lan Belmont",
    bpm: "172",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 9, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
    ],
    patchVersion: "1.08",
    imageUrl:
      "https://www.piugame.com/data/song_img/8d28848f0527248cbfc7456233242c92.png",
  },

  {
    name: "프ㄹi마 마테ㄹi아",
    artist: "xi",
    bpm: "187",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 14, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    patchVersion: "1.08",
    imageUrl:
      "https://www.piugame.com/data/song_img/d9ca9ba14be1f8d7bc007bfcae6f19a1.png",
  },

  // todo 2.00??

  // 2.01
  {
    name: " 디스코드",
    artist: "QWER",
    bpm: "132",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 3, chartType: "SINGLE" },
      { level: 6, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 8, chartType: "DOUBLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/468a5036181f048540d85bfb210b4486.png",
  },

  {
    name: "호랑이가 쫓아온다",
    artist: "DKZ",
    bpm: "128",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/9095d45d33d1c8cf8495c1295604e0af.png",
  },

  {
    name: " 호랑이가 쫓아온다",
    artist: "디케이지",
    bpm: "128",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 2, chartType: "SINGLE" },
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 9, chartType: "SINGLE" },
      { level: 14, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 11, chartType: "DOUBLE" },
      { level: 16, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/9095d45d33d1c8cf8495c1295604e0af.png",
  },

  {
    name: "하이웨이 체이서",
    artist: "Cosmograph",
    bpm: "155",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 13, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 22, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/f06cbde6cc0b8747421f52ac75b3ee8b.png",
  },

  {
    name: "에렌델",
    artist: "Palami feat.neur6sia",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 15, chartType: "DOUBLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/972549a9c03d8cc569270252aa405cf8.png",
  },

  {
    name: "러쉬-모어",
    artist: "litmus*",
    bpm: "160",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 13, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 17, chartType: "DOUBLE" },
      { level: 19, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/89ac6afc39e1dbaf27cede9586f53f2d.png",
  },

  {
    name: "메가하츠",
    artist: "DJ Noriken",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/557ee99561f8a1522c7c87f2a4a11a4e.png",
  },

  {
    name: "메가하츠",
    artist: "DJ Noriken",
    bpm: "200",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 23, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 25, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/557ee99561f8a1522c7c87f2a4a11a4e.png",
  },

  {
    name: "아테나의 방패",
    artist: "Jehezukiel",
    bpm: "176",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 4, chartType: "SINGLE" },
      { level: 7, chartType: "SINGLE" },
      { level: 11, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 20, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 14, chartType: "DOUBLE" },
      { level: 20, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/e9d9f977024488f5bb31c9e203621e84.png",
  },

  {
    name: "쵸빗 플레이버",
    artist: "aran & t+pazolite",
    bpm: "180",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 12, chartType: "SINGLE" },
      { level: 16, chartType: "SINGLE" },
      { level: 19, chartType: "SINGLE" },
      { level: 22, chartType: "SINGLE" },
      { level: 17, chartType: "SINGLE" },
      { level: 21, chartType: "DOUBLE" },
      { level: 24, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/0da2130360d6066534052ce19789e013.png",
  },

  {
    name: "프렉쳐 텀퍼렐르",
    artist: "Kurokotei",
    bpm: "232",
    version: "PHOENIX",
    songType: "ARCADE",
    charts: [
      { level: 9, chartType: "SINGLE" },
      { level: 12, chartType: "SINGLE" },
      { level: 15, chartType: "SINGLE" },
      { level: 18, chartType: "SINGLE" },
      { level: 21, chartType: "SINGLE" },
      { level: 24, chartType: "SINGLE" },
      { level: 18, chartType: "DOUBLE" },
      { level: 23, chartType: "DOUBLE" },
      { level: 26, chartType: "DOUBLE" },
    ],
    patchVersion: "2.01",
    imageUrl:
      "https://www.piugame.com/data/song_img/4f176d4f60c502692f8e1b0715e495e2.png",
  },
];
