name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Docker build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag piudb-web:$(date +%s)
